### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by Arkpocalypse** [irseny/RivaCross#2]
Hey thank you for the work! It works well so far (tested with Hunt:Showdown and Apex Legends)

Could you maybe add transparency to the crosshair? Maybe by extending the colour code to have the alpha at the end?

**Comment by irseny** [comment]
That is an awesome idea! I will try out whether thats possible with Riva Tuner when I get back to my usual setup and report back within around a week.

**Comment by Arkpocalypse** [comment]
Thanks! In RivaTuner you can set a transparency/opacity, but it doesn't change for the crosshair itself

**Comment by irseny** [comment]
Support for setting the transparency or alpha channel has been added to the latest prerelease which you can find here: https://github.com/irseny/RivaCross/releases
Let me know if this works and is sufficient for you.

**Comment by Arkpocalypse** [comment]
Works great, thanks again!
